# Generated by Django 2.1.7 on 2019-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_list',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('cgpa', models.FloatField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
