# Generated by Django 2.1.7 on 2019-09-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status Post', 'verbose_name_plural': 'Status Posts'},
        ),
    ]
