# Generated by Django 2.1.7 on 2019-09-16 19:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190911_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField()),
                ('approved_by', models.CharField(max_length=100)),
                ('outline', models.TextField()),
                ('prerequisits', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to=users.models.gen_filename)),
                ('private', models.BooleanField()),
                ('tags', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('fee', models.FloatField()),
            ],
        ),
    ]
