# Generated by Django 2.1.7 on 2019-09-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190917_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTable',
        ),
    ]
